#pragma once

namespace Alchemy::Compilation {

    enum class ErrorCode {
        None,
        ERR_IllegalEscape,
        ERR_OpenEndedComment,
        ERR_UnexpectedCharacter,
        ERR_InvalidReal,
        ERR_InvalidNumber,
        ERR_IntOverflow,
        ERR_InvalidRealNaN,
        ERR_InvalidRealInfinite,

        ERR_IdentifierExpectedKW,
        ERR_IdentifierExpected,
        ERR_SemicolonExpected,
        ERR_CloseParenExpected,
        ERR_LbraceExpected,
        ERR_RbraceExpected,
        ERR_SyntaxError,
        ERR_NoVoidParameter,
        ERR_NoVoidHere,
        ERR_ValueExpected,
        ERR_BadNewExpr,
        ERR_TypeExpected,
        ERR_TupleTooFewElements,
        ERR_TopLevelStatementAfterNamespaceOrType,
        ERR_EOFExpected,
        ERR_MultiTypeInDeclaration,
        ERR_BadVarDecl,
        ERR_ArraySizeInDeclaration,
        ERR_CStyleArray,
        ERR_ConstValueRequired,
        ERR_FixedDimsRequired,
        ERR_ThisOrBaseOrConstructorNameExpected,
        ERR_MissingArgument,
        ERR_UnexpectedSemicolon,
        ERR_SemiOrLBraceOrArrowExpected,
        ERR_InvalidExprTerm,
        ERR_ExpressionExpected,
        ERR_InvalidArray,
        ERR_InvalidStackAllocArray,
        ERR_UnexpectedToken,
        WRN_PrecedenceInversion,
        ERR_MissingPattern,
        ERR_UnexpectedDoubleColon,
    };

}