#pragma once

namespace Alchemy::Compilation {

    enum class ErrorCode {
        None,
        ERR_IllegalEscape,
        ERR_OpenEndedComment,
        ERR_UnexpectedCharacter,
        ERR_InvalidReal,
        ERR_InvalidNumber,
        ERR_IntOverflow,
        ERR_InvalidRealNaN,
        ERR_InvalidRealInfinite,

        ERR_IdentifierExpectedKW,
        ERR_IdentifierExpected,
        ERR_SemicolonExpected,
        ERR_CloseParenExpected,
        ERR_LbraceExpected,
        ERR_RbraceExpected,
        ERR_SyntaxError,
        ERR_NoVoidParameter,
        ERR_NoVoidHere,
        ERR_ValueExpected,
        ERR_BadNewExpr,
        ERR_TypeExpected,
        ERR_TupleTooFewElements,
        ERR_TopLevelStatementAfterNamespaceOrType,
        ERR_EOFExpected,
        ERR_MultiTypeInDeclaration,
        ERR_BadVarDecl,
        ERR_ArraySizeInDeclaration,
        ERR_CStyleArray,
        ERR_ConstValueRequired,
        ERR_FixedDimsRequired,
        ERR_ThisOrBaseOrConstructorNameExpected,
        ERR_MissingArgument,
        ERR_UnexpectedSemicolon,
        ERR_SemiOrLBraceOrArrowExpected,
        ERR_InvalidExprTerm,
        ERR_ExpressionExpected,
        ERR_InvalidArray,
        ERR_InvalidStackAllocArray,
        ERR_UnexpectedToken,
        ERR_UnexpectedKeyword,
        WRN_PrecedenceInversion,
        ERR_MissingPattern,
        ERR_UnexpectedDoubleColon,
        ERR_BadArraySyntax,
        ERR_BadCaseInSwitchArm,
        ERR_ExpectedForeachKeyword,
        ERR_BadForeachDecl,
        ERR_InExpected,
        ERR_ElseCannotStartStatement,
        ERR_BadMemberFlag,
        ERR_NoModifiersOnUsing,
        ERR_ExpectedEndTry,
        ERR_SwitchGoverningExpressionRequiresParens,
        ERR_ConstantExpected,
        ERR_DiscardPatternInSwitchStatement,
        ERR_InvalidMemberDecl,
        ERR_UnexpectedGenericName,
        ERR_NoDelegateConstraint,
        ERR_NewlineInConst,
        ERR_IllegalAtSequence,
        ERR_UnterminatedStringLiteral,
        ERR_UnterminatedCharacterLiteral,
        ERR_StringLiteralTooLong,
        ERR_EmptyCharLiteral,
        ERR_GetOrSetExpected,
        ERR_MulitpleVisibiltyDeclarations,
        ERR_OptionalParameterOrder,
        ERR_SealedOrAbstract,
        ERR_TypeCannotBeProtected,
        ERR_TypeCannotBeRef,
        ERR_MulitpleNamespaces,
        ERR_DuplicateUsingDirective,
        ERR_NamespaceMustComeBeforeUsingsAndDeclarations,
        ERR_UsingsMustComeBeforeDeclarations,
        ERR_DuplicateDeclaration,
        ERR_AmbiguousTypeMatch,
        ERR_UnresolvedType,
        ERR_TypeArgumentShouldNotBeAnExistingTypeName,
        ERR_OnlyFirstBaseTypeCanBeClass,
        ERR_CannotInheritASealedType,
        ERR_CannotInheritRecursively,
        ERR_StructsCanOnlyInheritInterfaces,
        ERR_BaseTypeInNonZeroPositionMustBeAnInterface,
        ERR_BaseTypeCannotBeRef,
        ERR_BaseTypeCannotBeNullable,
        ERR_BaseTypeCannotBeTuple,
        ERR_CycleDetectedInClassHierarchy,
        ERR_BaseTypeAppearsMultipleTimes,
        ERR_MultipleVisibilityModifiers,
        ERR_MultipleModifiers,
        ERR_StaticIsExclusiveWithConst,
        ERR_ReadOnlyIsExclusiveWithConst,

        ERR_InvalidModifierForFieldDeclaration,

        ERR_OverrideIsExclusiveWithSealed,
        ERR_OverrideIsExclusiveWithVirtual,
        ERR_OverrideIsExclusiveWithStatic,
        ERR_OverrideIsExclusiveWithAbstract,

        ERR_StaticIsExclusiveWithSealed,
        ERR_StaticIsExclusiveWithVirtual,
        ERR_StaticIsExclusiveWithAbstract,
        ERR_StaticIsExclusiveWithOverride,

        ERR_SealedIsExclusiveWithStatic,
        ERR_SealedIsExclusiveWithVirtual,
        ERR_SealedIsExclusiveWithAbstract,
        ERR_SealedIsExclusiveWithOverride,

        ERR_AbstractIsExclusiveWithSealed,
        ERR_AbstractIsExclusiveWithVirtual,
        ERR_AbstractIsExclusiveWithOverride,
        ERR_AbstractIsExclusiveWithStatic,

        ERR_VirtualIsExclusiveWithSealed,
        ERR_VirtualIsExclusiveWithAbstract,
        ERR_VirtualIsExclusiveWithOverride,
        ERR_VirtualIsExclusiveWithStatic,

        ERR_ReadOnlyIsExclusiveWithOutAndRef,
        ERR_RefIsExclusiveWithOutAndReadonly,
        ERR_OutIsExclusiveWithRefAndReadonly,
        ERR_InvalidModifierForParameterDeclaration,
        ERR_InvalidModifierForMethodDeclaration,
        ERR_DuplicateParameterName,


        ERR_ExpectedReturnType,
        ERR_DuplicateIdentifierInScope,
        ERR_InstanceFieldAccessInStaticContext,
    };

}